// src/pages/TourGuideFeedback.tsx
// ─────────────────────────────────────────────────────────────────────────────
// Route: /feedback/:sessionId
// Reached when a tourist scans the QR generated by FeedbackQR.tsx.
//
// Flow:
//   1. Load the session (getSession) → guideId, guideName, destinationName.
//   2. Check if this tourist already submitted feedback for this session.
//   3. Show the rating form → submit → thank-you state.
// ─────────────────────────────────────────────────────────────────────────────

import React, { useState, useEffect } from 'react';
import {
  IonPage,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonContent,
  IonIcon,
  IonButton,
  IonSpinner,
  IonTextarea,
  IonToast,
} from '@ionic/react';
import { useParams, useHistory } from 'react-router-dom';
import {
  arrowBackOutline,
  star,
  starOutline,
  checkmarkCircleOutline,
  personCircleOutline,
} from 'ionicons/icons';
import { useAuth } from '../../../context/AuthContext';
import { getSession, TourSession } from '../../../services/sessionService';
import {
  hasSubmittedFeedback,
  submitGuideFeedback,
} from '../../../services/feedbackService';
import './TourGuideFeedback.css';

interface RouteParams {
  sessionId: string;
}

type CategoryKey = 'knowledge' | 'friendliness' | 'punctuality' | 'communication';

const CATEGORIES: { key: CategoryKey; label: string }[] = [
  { key: 'knowledge', label: 'Knowledge' },
  { key: 'friendliness', label: 'Friendliness' },
  { key: 'punctuality', label: 'Punctuality' },
  { key: 'communication', label: 'Communication' },
];

const TourGuideFeedback: React.FC = () => {
  const { sessionId } = useParams<RouteParams>();
  const history = useHistory();
  const { currentUser } = useAuth();

  const [loading, setLoading] = useState(true);
  const [session, setSession] = useState<TourSession | null>(null);
  const [alreadySubmitted, setAlreadySubmitted] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [toastMsg, setToastMsg] = useState('');

  const [overallRating, setOverallRating] = useState(0);
  const [categoryRatings, setCategoryRatings] = useState<Record<CategoryKey, number>>({
    knowledge: 0,
    friendliness: 0,
    punctuality: 0,
    communication: 0,
  });
  const [comment, setComment] = useState('');

  // ── Load session + check prior submission ──────────────────────────────
  useEffect(() => {
    if (!sessionId) {
      setLoading(false);
      return;
    }

    const load = async () => {
      try {
        const data = await getSession(sessionId);
        setSession(data);

        if (data && currentUser) {
          const already = await hasSubmittedFeedback(sessionId, currentUser.uid);
          setAlreadySubmitted(already);
        }
      } catch (err) {
        console.error('Failed to load session:', err);
      } finally {
        setLoading(false);
      }
    };

    load();
  }, [sessionId, currentUser]);

  const handleCategoryRate = (key: CategoryKey, value: number) => {
    setCategoryRatings(prev => ({ ...prev, [key]: value }));
  };

  const handleSubmit = async () => {
    if (!session || !currentUser) return;

    if (overallRating === 0) {
      setToastMsg('Please give an overall star rating.');
      return;
    }

    setSubmitting(true);
    try {
      await submitGuideFeedback({
        sessionId,
        guideId: session.guideId,
        guideName: session.guideName,
        destinationId: session.destinationId,
        destinationName: session.destinationName,
        touristId: currentUser.uid,
        touristName: currentUser.displayName || 'Tourist',
        rating: overallRating,
        categoryRatings,
        comment,
      });
      setSubmitted(true);
    } catch (err) {
      console.error('Failed to submit feedback:', err);
      setToastMsg('Something went wrong. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  // ── Star row (interactive) ──────────────────────────────────────────────
  const StarRow: React.FC<{
    value: number;
    onChange: (v: number) => void;
    size?: 'lg' | 'sm';
  }> = ({ value, onChange, size = 'lg' }) => (
    <div className={`tf-star-row tf-star-row--${size}`}>
      {[1, 2, 3, 4, 5].map((n) => (
        <IonIcon
          key={n}
          icon={n <= value ? star : starOutline}
          className={`tf-star tf-star--${size} ${n <= value ? 'tf-star--filled' : ''}`}
          onClick={() => onChange(n)}
        />
      ))}
    </div>
  );

  // ── Loading ──────────────────────────────────────────────────────────────
  if (loading) {
    return (
      <IonPage>
        <IonContent className="tf-content">
          <div className="tf-loading">
            <IonSpinner name="crescent" />
            <p>Loading tour details…</p>
          </div>
        </IonContent>
      </IonPage>
    );
  }

  // ── Session not found ────────────────────────────────────────────────────
  if (!session) {
    return (
      <IonPage>
        <IonContent className="tf-content">
          <div className="tf-error">
            <IonIcon icon={checkmarkCircleOutline} />
            <p>This feedback link isn't valid.</p>
            <span>Please scan the QR code your guide provided.</span>
            <IonButton className="tf-home-btn" onClick={() => history.push('/home')}>
              Go Home
            </IonButton>
          </div>
        </IonContent>
      </IonPage>
    );
  }

  // ── Thank-you state (just submitted, or already submitted before) ───────
  if (submitted || alreadySubmitted) {
    return (
      <IonPage>
        <IonContent className="tf-content">
          <div className="tf-thanks">
            <div className="tf-thanks-icon">
              <IonIcon icon={checkmarkCircleOutline} />
            </div>
            <h2>Thank you!</h2>
            <p>
              {submitted
                ? `Your feedback for ${session.guideName} has been submitted.`
                : `You've already shared your feedback for this tour.`}
            </p>
            <IonButton className="tf-home-btn" onClick={() => history.push('/home')}>
              Back to Home
            </IonButton>
          </div>
        </IonContent>
      </IonPage>
    );
  }

  // ── Form ──────────────────────────────────────────────────────────────────
  return (
    <IonPage>
      <IonHeader className="ion-no-border">
        <IonToolbar className="tf-header">
          <div onClick={() => history.goBack()} className="tf-back-btn">
            <IonIcon icon={arrowBackOutline} />
          </div>
          <IonTitle className="tf-title">RATE YOUR TOUR</IonTitle>
        </IonToolbar>
      </IonHeader>

      <IonContent className="tf-content">
        <div className="tf-wrapper">

          {/* Guide hero */}
          <div className="tf-hero">
            <div className="tf-guide-avatar">
              <IonIcon icon={personCircleOutline} />
            </div>
            <h2>{session.guideName}</h2>
            <p>{session.destinationName}</p>
          </div>

          {/* Overall rating */}
          <div className="tf-card">
            <span className="tf-card-label">How was your overall experience?</span>
            <StarRow value={overallRating} onChange={setOverallRating} size="lg" />
          </div>

          {/* Category ratings */}
          <div className="tf-card">
            <span className="tf-card-label">Rate specific aspects (optional)</span>
            <div className="tf-category-list">
              {CATEGORIES.map(({ key, label }) => (
                <div className="tf-category-row" key={key}>
                  <span className="tf-category-name">{label}</span>
                  <StarRow
                    value={categoryRatings[key]}
                    onChange={(v) => handleCategoryRate(key, v)}
                    size="sm"
                  />
                </div>
              ))}
            </div>
          </div>

          {/* Comment */}
          <div className="tf-card">
            <span className="tf-card-label">Tell us more (optional)</span>
            <IonTextarea
              className="tf-textarea"
              placeholder="What did you enjoy? Anything we could improve?"
              value={comment}
              onIonChange={(e) => setComment(e.detail.value || '')}
              autoGrow
              rows={4}
              maxlength={500}
            />
          </div>

          <IonButton
            expand="block"
            className="tf-submit-btn"
            disabled={submitting}
            onClick={handleSubmit}
          >
            {submitting ? <IonSpinner name="crescent" /> : 'Submit Feedback'}
          </IonButton>

        </div>
      </IonContent>

      <IonToast
        isOpen={!!toastMsg}
        message={toastMsg}
        duration={3000}
        position="bottom"
        onDidDismiss={() => setToastMsg('')}
      />
    </IonPage>
  );
};

export default TourGuideFeedback;
