// src/pages/Settings/Scan.tsx
// ─────────────────────────────────────────────────────────────────────────────
// QR-code scanner page. Recognizes TWO QR formats:
//   1. Tour-session QR (created by the guide) → joins the session.
//   2. Destination QR (created in the admin panel, /destination?id=<docId>)
//      → records a confirmed visit, fires the AI proximity guide as a
//        GPS-independent backup trigger, then opens the destination page.
// ─────────────────────────────────────────────────────────────────────────────

import React, { useEffect, useRef, useState, useCallback } from 'react';
import {
  IonPage, IonHeader, IonToolbar, IonTitle, IonContent,
  IonButtons, IonBackButton, IonIcon, IonToast,
} from '@ionic/react';
import { useIonRouter } from '@ionic/react';
import {
  qrCodeOutline, flashOutline, flashOffOutline,
  imageOutline, checkmarkCircle, alertCircleOutline,
  refreshOutline,
} from 'ionicons/icons';
import { Html5Qrcode, Html5QrcodeSupportedFormats } from 'html5-qrcode';

// Firebase
import { collection, addDoc, doc, getDoc } from 'firebase/firestore';
import { fetchDestinationById } from '../../../services/destinationService';
import { useProximityAIOptional } from '../../../context/Proximityaicontext';
import { auth, firestore } from '../../../firebase';
import { Destination } from '../../../types';
import { createNotification, notifyVisitRecorded } from '../../../services/notificationsService';
import { checkInTouristToSession } from '../../../services/sessionService';

import './Scan.css';

// ── Firebase helpers ─────────────────────────────────────────────────────────────
// Use the shared app initialization from src/firebase.ts so the same auth
// instance and Firestore config are reused across the app.
const db = firestore;

// ── Helpers ───────────────────────────────────────────────────────────────────
/**
 * Given any supported QR payload string, extract the session ID.
 * The QR generated by GenerateQR.tsx contains the plain session ID with no
 * fixed length requirement — so we no longer gate on an arbitrary character
 * count (that was rejecting valid, shorter session/join codes and causing
 * "QR code not recognised" for perfectly good session QRs).
 *
 * Instead we positively identify the two known payload shapes:
 *   1. A URL — only counts as a session if it matches /tour-session/...
 *      (any other URL, e.g. the admin's /destination?id=... QR, is left
 *      alone for extractDestinationId to handle).
 *   2. Not a URL — treated as a raw session ID as long as it's non-empty
 *      and isn't broken up by whitespace/newlines (which would indicate
 *      it's not an ID at all).
 */
function extractSessionId(raw: string): string | null {
  const trimmed = raw.trim();
  if (!trimmed) return null;

  if (trimmed.startsWith('http')) {
    try {
      const url = new URL(trimmed);
      // Support /tour-session/<id>
      const match = url.pathname.match(/\/tour-session\/([A-Za-z0-9_-]+)/);
      if (match) return match[1];
      // Support /tour-session?id=<id>
      const qid = url.searchParams.get('id');
      if (url.pathname.includes('/tour-session') && qid) return qid;
    } catch { /* Not a valid URL — fall through to null below */ }
    // Any other URL (e.g. a /destination?id=... QR) is NOT a session.
    return null;
  }

  // Plain, non-URL payload — accept as a raw session ID.
  if (!trimmed.includes(' ') && !trimmed.includes('\n')) {
    return trimmed;
  }

  return null;
}

/**
 * Given any supported QR payload string, extract a feedback-session ID.
 * This is the QR shown on FeedbackQR.tsx AFTER a tour ends — it's a
 * DIFFERENT QR from the tour-join QR handled by extractSessionId above,
 * even though both encode a sessionId. It points at `/feedback/<sessionId>`
 * (TourGuideFeedback.tsx's route) instead of `/tour-session/<sessionId>`.
 */
function extractFeedbackSessionId(raw: string): string | null {
  const trimmed = raw.trim();
  // Support both full URLs (https://.../feedback/:id) and plain path
  // payloads like `/feedback/<id>` or `feedback/<id>` which some scanners
  // may produce when copying a short link.
  const tryMatchPath = (path: string) => {
    const m = path.match(/\/?feedback\/([A-Za-z0-9_-]+)/);
    return m ? m[1] : null;
  };

  if (trimmed.startsWith('http')) {
    try {
      const url = new URL(trimmed);
      return tryMatchPath(url.pathname);
    } catch {
      return null;
    }
  }

  // Fallback: handle raw path-like payloads (e.g. `/feedback/abc123`)
  return tryMatchPath(trimmed);
}

/**
 * Given any supported QR payload string, extract a destination ID.
 * Matches the format the admin panel actually generates:
 *   `${origin}/destination?id=<docId>`
 * (see destinations_page.ts → generateQrCode). This is a DIFFERENT QR type
 * from the guide's tour-session QR handled by extractSessionId above.
 */
function extractDestinationId(raw: string): string | null {
  const trimmed = raw.trim();
  if (!trimmed.startsWith('http')) return null;
  try {
    const url = new URL(trimmed);
    if (!url.pathname.includes('/destination')) return null;
    return url.searchParams.get('id');
  } catch {
    return null;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
const Scan: React.FC = () => {
  const router = useIonRouter();
  // Optional: Scan still works fully (session join, destination check-in,
  // visit logging) even if <ProximityAIProvider> isn't wired into App.tsx yet.
  const proximityAI = useProximityAIOptional();

  const scannerRef    = useRef<Html5Qrcode | null>(null);
  const viewfinderRef = useRef<HTMLDivElement>(null);

  const [scanning,   setScanning]   = useState(false);
  const [torchOn,    setTorchOn]    = useState(false);
  const [scanResult, setScanResult] = useState<'success' | 'error' | null>(null);
  const [resultMsg,  setResultMsg]  = useState('');
  const [toastMsg,   setToastMsg]   = useState('');
  const [cameraErr,  setCameraErr]  = useState('');
  const [lastScan,   setLastScan]   = useState('');  // debounce

  // Always-current pointer to handleScanSuccess. startScanner is memoized
  // with [] (it's only ever created once, on mount), so any function it
  // closes over directly would be permanently frozen to its first-render
  // version — including a stale `lastScan` inside handleScanSuccess, which
  // silently broke the duplicate-scan debounce. Routing the call through a
  // ref that's updated every render fixes that without having to rebuild
  // the camera on every keystroke/state change.
  const handleScanSuccessRef = useRef<(raw: string) => void>(() => {});

  // ── Start camera ───────────────────────────────────────────────────────────
  const startScanner = useCallback(async () => {
    setCameraErr('');
    setScanResult(null);
    setResultMsg('');

    try {
      const qr = new Html5Qrcode('qr-viewfinder', {
        formatsToSupport: [Html5QrcodeSupportedFormats.QR_CODE],
        verbose: false,
      });
      scannerRef.current = qr;

      await qr.start(
        { facingMode: 'environment' },
        { fps: 10, qrbox: { width: 240, height: 240 } },
        (decodedText) => { handleScanSuccessRef.current(decodedText); },
        () => { /* scan errors are normal – ignore */ }
      );

      setScanning(true);
    } catch (err: any) {
      console.error('[Scan] camera start failed:', err);
      setCameraErr(
        err?.message?.includes('Permission')
          ? 'Camera permission denied. Please allow camera access in your browser settings.'
          : 'Could not start camera. Make sure no other app is using it.'
      );
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Stop camera ────────────────────────────────────────────────────────────
  const stopScanner = useCallback(async () => {
    try {
      if (scannerRef.current?.isScanning) {
        await scannerRef.current.stop();
      }
    } catch { /* ignore */ }
    scannerRef.current = null;
    setScanning(false);
    setTorchOn(false);
  }, []);

  // ── Lifecycle ──────────────────────────────────────────────────────────────
  useEffect(() => {
    startScanner();
    return () => { stopScanner(); };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Handle scan result ─────────────────────────────────────────────────────
  const handleScanSuccess = useCallback(async (raw: string) => {
    // Debounce — ignore repeated identical scans within 3 s
    if (raw === lastScan) return;
    setLastScan(raw);
    setTimeout(() => setLastScan(''), 3000);

    const sessionId = extractSessionId(raw);

    if (sessionId) {
      try {
        const user = auth.currentUser;
        if (!user) {
          setScanResult('error');
          setResultMsg('Please log in before joining a tour.');
          return;
        }

        let isEmailVerified = user.emailVerified;

        const userDoc = await getDoc(doc(firestore, 'users', user.uid));
        if (userDoc.exists()) {
          const profile = userDoc.data() as any;
          isEmailVerified = user.emailVerified || profile?.emailVerified === true;
        }

        if (!isEmailVerified) {
          setScanResult('error');
          setResultMsg('Please verify your profile before joining a tour.');
          return;
        }

        const sessionSnap = await getDoc(doc(firestore, 'sessions', sessionId));
        if (!sessionSnap.exists()) {
          setScanResult('error');
          setResultMsg('This tour session does not exist. Please scan a valid code.');
          setTimeout(() => {
            setScanResult(null);
            setResultMsg('');
            setLastScan('');
          }, 3000);
          return;
        }

        const sessionData = sessionSnap.data() as any;
        if (sessionData?.status === 'ended' || sessionData?.status === 'Cancelled') {
          setScanResult('error');
          setResultMsg(sessionData?.status === 'Cancelled'
            ? 'This tour was cancelled and cannot be joined.'
            : 'This tour has already ended and cannot be joined.');
          setTimeout(() => {
            setScanResult(null);
            setResultMsg('');
            setLastScan('');
          }, 3000);
          return;
        }

        // The QR confirms attendance only. Registration must already exist
        // from the /tour join flow; an unregistered scan stays on this page.
        await checkInTouristToSession(sessionId, user.uid);
        await createNotification({
          userId: user.uid,
          type: 'checked_in',
          title: 'Attendance confirmed',
          message: `Your attendance is confirmed for ${sessionData.destinationName || 'this tour'}.`,
          sessionId,
        });
      } catch (err: any) {
        console.warn('[Scan] session join failed:', err);
        setScanResult('error');
        setResultMsg(err?.message || 'Unable to join this tour. Please try again.');
        setTimeout(() => {
          setScanResult(null);
          setResultMsg('');
          setLastScan('');
        }, 3500);
        return;
      }

      stopScanner();
      setScanResult('success');
      setResultMsg('Joining tour session…');

      // Navigate to the tour session page
      setTimeout(() => router.push(`/tour-session/${sessionId}`, 'forward'), 800);
      return;
    }

    // Not a session-join QR — check if it's the guide's post-tour feedback QR
    const feedbackSessionId = extractFeedbackSessionId(raw);

    if (feedbackSessionId) {
      stopScanner();
      setScanResult('success');
      setResultMsg('Opening feedback form…');
      setTimeout(() => router.push(`/feedback/${feedbackSessionId}`, 'forward'), 800);
      return;
    }

    // Not a session or feedback QR — check if it's the admin's destination QR instead
    // (format: `${origin}/destination?id=<docId>`, generated in the admin panel).
    const destinationId = extractDestinationId(raw);

    if (destinationId) {
      stopScanner();
      setScanResult('success');
      setResultMsg('Destination confirmed!');

      try {
        const destination = await fetchDestinationById(destinationId);

        if (destination) {
          // QR check-in is a CONFIRMED visit — unlike GPS proximity pings,
          // this is safe to count toward Home's "#rank" ribbons.
          const name = (destination as any).title || (destination as any).name || '';
          try {
            const userId = auth.currentUser?.uid ?? null;
            await addDoc(collection(firestore, 'visits'), {
              destinationTop: name,
              destinationId,
              scannedAt: new Date().toISOString(),
              ...(userId ? { userId } : {}),
            });
            if (userId) await notifyVisitRecorded(userId, name, destinationId);
          } catch (err) {
            console.warn('[Scan] visit record failed (non-fatal):', err);
          }

          // Confirmed backup trigger for the AI proximity guide — bypasses
          // the GPS radius check, useful indoors or when GPS drifts.
          // No-op if <ProximityAIProvider> isn't mounted.
          void proximityAI?.triggerForDestination(destination, 'qr');
        } else {
          console.warn('[Scan] destination not found for id:', destinationId);
        }
      } catch (err) {
        console.warn('[Scan] destination lookup failed (non-fatal):', err);
      }

      setTimeout(() => router.push(`/destination/${destinationId}`, 'forward'), 800);
    } else {
      setScanResult('error');
      setResultMsg(`QR code not recognised.\n"${raw}"`);
      // Auto-reset after 3 s so user can try again
      setTimeout(() => {
        setScanResult(null);
        setResultMsg('');
        setLastScan('');
      }, 3000);
    }
  }, [lastScan, router, stopScanner, proximityAI]);

  useEffect(() => {
    handleScanSuccessRef.current = handleScanSuccess;
  }, [handleScanSuccess]);

  // ── Torch toggle ──────────────────────────────────────────────────────────
  const toggleTorch = async () => {
    if (!scannerRef.current?.isScanning) return;
    try {
      const track = (scannerRef.current as any)?.videoElement
        ?.srcObject?.getVideoTracks?.()[0];
      if (track?.applyConstraints) {
        await track.applyConstraints({ advanced: [{ torch: !torchOn } as any] });
        setTorchOn(t => !t);
      } else {
        setToastMsg('Torch not supported on this device.');
      }
    } catch {
      setToastMsg('Torch not supported on this device.');
    }
  };

  // ── Image file fallback ───────────────────────────────────────────────────
  const handleFileScan = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    e.target.value = '';

    // html5-qrcode refuses to run scanFile() on an instance that's mid-`start()`
    // (i.e. the live camera is actively scanning) — it throws, and that error
    // was previously being swallowed below and shown as a generic
    // "No QR code found" message regardless of what actually went wrong.
    // Stop the camera first so the file scan gets a clean instance.
    const wasScanning = !!scannerRef.current?.isScanning;
    if (wasScanning) {
      await stopScanner();
    }

    let qr = scannerRef.current;
    if (!qr) {
      qr = new Html5Qrcode('qr-viewfinder', { verbose: false });
      scannerRef.current = qr;
    }

    try {
      const result = await qr.scanFile(file, true);
      handleScanSuccess(result);
    } catch (err) {
      console.error('[Scan] file scan failed:', err);
      setToastMsg('No QR code found in the selected image.');
      // The camera was running before — bring it back so the user can retry.
      if (wasScanning) startScanner();
    }
  };

  // ── Render ─────────────────────────────────────────────────────────────────
  return (
    <IonPage>
      <IonHeader>
        <IonToolbar className="scan-toolbar">
          <IonButtons slot="start"><IonBackButton defaultHref="/settings" /></IonButtons>
          <IonTitle>Scan QR Code</IonTitle>
          <IonButtons slot="end">
            <button className="scan-hdr-btn" onClick={toggleTorch} disabled={!scanning} aria-label="Toggle torch">
              <IonIcon icon={torchOn ? flashOutline : flashOffOutline} />
            </button>
          </IonButtons>
        </IonToolbar>
      </IonHeader>

      <IonContent className="scan-content" scrollY={false}>

        {/* ── Camera viewfinder ──────────────────────────────────────────── */}
        <div className="scan-camera-wrap">
          <div id="qr-viewfinder" ref={viewfinderRef} className="scan-viewfinder" />

          {/* Overlay frame + corners */}
          <div className="scan-frame-overlay">
            <div className="scan-corner scan-corner--tl" />
            <div className="scan-corner scan-corner--tr" />
            <div className="scan-corner scan-corner--bl" />
            <div className="scan-corner scan-corner--br" />
            {scanning && !scanResult && <div className="scan-laser" />}
          </div>

          {/* Success / error overlay */}
          {scanResult === 'success' && (
            <div className="scan-result-overlay scan-result-overlay--success">
              <IonIcon icon={checkmarkCircle} className="scan-result-icon" />
              <p className="scan-result-msg">{resultMsg}</p>
            </div>
          )}
          {scanResult === 'error' && (
            <div className="scan-result-overlay scan-result-overlay--error">
              <IonIcon icon={alertCircleOutline} className="scan-result-icon" />
              <p className="scan-result-msg">{resultMsg}</p>
            </div>
          )}

          {/* Camera error */}
          {cameraErr && (
            <div className="scan-cam-error">
              <IonIcon icon={alertCircleOutline} className="scan-cam-err-icon" />
              <p>{cameraErr}</p>
              <button className="scan-retry-btn" onClick={startScanner}>
                <IonIcon icon={refreshOutline} /> Retry
              </button>
            </div>
          )}
        </div>

        {/* ── Instructions ──────────────────────────────────────────────── */}
        <div className="scan-instructions">
          <IonIcon icon={qrCodeOutline} className="scan-inst-icon" />
          <p className="scan-inst-title">Point camera at a QR code</p>
          <p className="scan-inst-sub">Tour session, feedback, or destination QR codes all work.</p>
        </div>

        {/* ── Action buttons ─────────────────────────────────────────────── */}
        <div className="scan-actions">
          <label className="scan-action-btn scan-action-btn--secondary">
            <IonIcon icon={imageOutline} />
            <span>Upload QR Image</span>
            <input name="scan-photo" type="file" accept="image/*" onChange={handleFileScan} className="scan-file-input" />
          </label>

          {!scanning && !cameraErr && (
            <button className="scan-action-btn scan-action-btn--primary" onClick={startScanner}>
              <IonIcon icon={refreshOutline} />
              <span>Restart Camera</span>
            </button>
          )}
        </div>

        <IonToast
          isOpen={!!toastMsg}
          message={toastMsg}
          duration={2500}
          position="bottom"
          onDidDismiss={() => setToastMsg('')}
        />
      </IonContent>
    </IonPage>
  );
};

export default Scan;
